# docker-compose.yml
version: '3'

services:

  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/simple
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=simple.settings
      - SECRET_KEY=django-insecure-m$$&h0029o&8lf4jibnoyz%c$$o#rl^cx&xd)fvl*leu*!v2ju9%
    ports:
      - "8000:8000"

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

volumes:
  postgres_data:
